// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { existsSync } from "fs"
import { config } from "dotenv"
import { defineConfig } from "prisma/config";

// Carga .env.local primero (desarrollo local), luego .env como fallback
if (existsSync(".env.local")) config({ path: ".env.local" })
else config({ path: ".env" })

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
